name: Run Slack Bot

on:
  schedule:
    - cron: '0 10 * * *'  # Every day at 10:00 UTC
  workflow_dispatch:       # Allow manual run

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Write Google credentials to file
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > creds.json

      - name: Run Slack bot
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python your_script.py
